baseURL: 'https://rs-loves-bugs.github.io'
languageCode: 'en-us'
title: '_rs'
theme: "hugo-xmin"
disableHugoGeneratorInject: true
googleAnalytics: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Contact
      url: "contact/"
      weight: 2

